### ISSUE TITLE
Make API backendURL adjustable

### ISSUE THREAD

**Issue by MuskallaEwerk** [mattevans/postmark-go#8]
Postmark deprecated static IPs for their API. In some infrastructures, this poses an issue since DNS resolving isn't always possible. In our case, we use a proxy to connect to the API to circumvent this. However, to be able to use a proxy with this package we would need to adjust the backendURL. As it stands now, it is fixed as a constant. Would it be possible to introduce a change to this so we can easily adjust the URL?

**Comment by mattevans** [comment]
Hi @MuskallaEwerk 

This is now possible, added in https://github.com/mattevans/postmark-go/pull/9

Upgrade to `v1.0.0`.

You client can now be initialised as follows...

```go
		client = postmark.NewClient(
			postmark.WithClient(&http.Client{
				Transport: &postmark.AuthTransport{Token: "YOUR_TOKEN"},
			}),
			postmark.WithBackendURL("https://your-url.com/slug"),
		)
```
